
default: &default
  adapter: postgresql
  encoding: unicode
  username: dthomas
  password: 1234
  pool: 5

development:
  <<: *default
  database: new_speak_development

test:
  <<: *default
  database: new_speak_test

production:
  <<: *default
  database: new_speak_production
  username: dinkan
  password: <%= ENV['DINKAN_DATABASE_PASSWORD'] %>